### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by swjz** [sjyk/deeplens-cv#8]
- [ ] not iterating between batches, and starting over. new video reader each time with offset.
- [ ] splitting function; might not work with real data
- [ ] crop['all'], e.g. frame by frame data
- [ ] joining videos aren't working
- [ ] union of all objects is almost the same as the entire video
- [ ] state of storage. restart each time
- [ ] better query with overlapping objects
- [x] make limit work

@j2zhao @swjz

**Comment by swjz** [comment]
- [ ] Idempotent `put`: when `put` gets called multiple times, make sure no error is raised and our database still looks good

**Comment by swjz** [comment]
- [ ] feedback implementation
- [ ] materialization implementation
- [ ] define types and type checking for operators
- [ ] serialize all ops
- [ ] support custom datastream map & buffermap
- [ ] get() tests
